# Generated by Django 5.0.6 on 2024-07-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mysigninform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'signin',
            },
        ),
        migrations.CreateModel(
            name='Registermovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Year', models.IntegerField()),
                ('Rateing', models.CharField(max_length=30)),
                ('categories', models.CharField(max_length=30)),
                ('Durection', models.CharField(max_length=20)),
                ('descriptions', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='movie')),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
