# Generated by Django 5.0.6 on 2024-07-03 05:26

import django.utils.timezone
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starstreaming', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermovie',
            name='Rateing',
        ),
        migrations.AddField(
            model_name='registermovie',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registermovie',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
