# Generated by Django 5.0.6 on 2024-07-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starstreaming', '0002_remove_registermovie_rateing_registermovie_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermovie',
            name='added',
        ),
        migrations.AlterField(
            model_name='registermovie',
            name='video',
            field=models.FileField(upload_to='video'),
        ),
    ]
